<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUxqM27n\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUxqM27n/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUxqM27n.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUxqM27n\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUxqM27n\App_KernelDevDebugContainer([
    'container.build_hash' => 'UxqM27n',
    'container.build_id' => 'aa528f37',
    'container.build_time' => 1610035495,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUxqM27n');
