<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJfeoZ4W\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJfeoZ4W/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJfeoZ4W.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJfeoZ4W\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJfeoZ4W\App_KernelDevDebugContainer([
    'container.build_hash' => 'JfeoZ4W',
    'container.build_id' => 'c324cea5',
    'container.build_time' => 1610104862,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJfeoZ4W');
