<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
    'app_cart_getcart' => [['uid'], ['_controller' => 'App\\Controller\\CartController::getCart'], [], [['variable', '/', '[^/]++', 'uid', true], ['text', '/cart']], [], []],
    'app_cart_addproduct' => [['uid'], ['_controller' => 'App\\Controller\\CartController::addProduct'], [], [['variable', '/', '[^/]++', 'uid', true], ['text', '/cart']], [], []],
];
