<?php

namespace ContainerUxqM27n;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGetAndPostService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\GetAndPost' shared autowired service.
     *
     * @return \App\Controller\GetAndPost
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Controller/GetAndPost.php';

        return $container->services['App\\Controller\\GetAndPost'] = new \App\Controller\GetAndPost();
    }
}
